# Generated by Django 4.2.2 on 2023-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Application"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=15, unique=True, verbose_name="URL"),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["id"],
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
