# Generated by Django 4.2.2 on 2023-06-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_application_alter_contact_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datatype",
            name="data_type",
            field=models.CharField(
                blank=True, db_index=True, max_length=10, null=True, verbose_name="Type"
            ),
        ),
    ]
