# Generated by Django 4.2.2 on 2023-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_email_field_type_alter_phonenumber_field_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="field_type",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("work", "Work"), ("personal", "Personal")],
                default="",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="field_type",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("work", "Work"), ("personal", "Personal")],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
