# Generated by Django 4.2.2 on 2023-06-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_datatype_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="field_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contacts.datatype",
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="field_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contacts.datatype",
                verbose_name="Type",
            ),
        ),
    ]
