# Generated by Django 4.2.2 on 2023-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="files/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("images", "Images"),
                            ("documents", "Documents"),
                            ("videos", "Videos"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
