# Generated by Django 4.2.2 on 2023-06-14 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="upload_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
