# Generated by Django 4.2.2 on 2023-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=25),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="unique_tag_per_user"
            ),
        ),
    ]
