# Generated by Django 4.2.2 on 2023-06-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0002_alter_tag_name_tag_unique_tag_per_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="note",
            name="importance",
            field=models.CharField(
                choices=[("", "None"), ("1", "Low"), ("2", "Medium"), ("3", "High")],
                default="",
                max_length=6,
            ),
        ),
    ]
