# Generated by Django 4.2.2 on 2023-06-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0005_alter_note_importance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="importance",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("1", "1 - Low"),
                    ("2", "2 - Medium"),
                    ("3", "3 - High"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
