# Generated by Django 4.2.2 on 2023-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("noteapp", "0006_alter_note_importance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="importance",
            field=models.CharField(
                choices=[
                    ("", "None"),
                    ("1 - low", "Low"),
                    ("2 - medium", "Medium"),
                    ("3 - high", "High"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
